/*
SCRIPT DE LIMPEZA DE PROCESSOS E DOCUMENTOS DA BASE DE DADOS DO SEI 4.1.0 (ORACLE)
  Antes de executar o script:
    1) Retirar o sistema do "AR" (derrubar todas sessõµes).
    2) Fazer uma cópia da base imediatamente antes de executar o script.
    3) Executar o script de limpeza. Se der erro, restaurar a base com a cópia feita no passo 2.

  Depois de executar o script com sucesso, sendo aconselhável conferir algumas tabelas abaixo e sequenciais de protocolo de processo na tabela "infra_sequencia":
    1) Apagar todos os arquivos e estrutura de pastas no Filesystem do sei_esquema.
    2) Excluir os Índices do Solr, conforme orientado no final do capítulo do Solr no Manual de Instalação do SEI:
      18 - Caso,  no  futuro,  seja  preciso  reindexar  todos  os  dados  é  aconselhável  limpar  antes  os  Índices usando os comandos abaixo:
        http://[servidor_solr]:8080/solr/sei-protocolos/update?stream.body=<delete><query>*:*</query></delete>&commit=true
				http://[servidor_solr]:8080/solr/sei-bases-conhecimento/update?stream.body=<delete><query>*:*</query></delete>&commit=true
				http://[servidor_solr]:8080/solr/sei-publicacoes/update?stream.body=<delete><query>*:*</query></delete>&commit=true
		4) Colocar o sistema de volta ao "AR".
*/

connect sei_esquema/sei_esquema@teste
 
/* Limpeza de tabelas afetas a Protocolo de Processos, de Documentos Gerados e Externos */


spool disable_fk.sql
select 'ALTER TABLE '||cons.table_name||' DISABLE CONSTRAINT '||constraint_name||' CASCADE;'
from   user_tables tabs
       INNER JOIN user_constraints cons on (cons.table_name = tabs.table_name)       
where cons.CONSTRAINT_TYPE = 'R';
spool off
@disable_fk.sql;
/
--Fim - Desabilitando as FKs


TRUNCATE TABLE ACAO_FEDERACAO;
TRUNCATE TABLE ACESSO;
TRUNCATE TABLE ACESSO_EXTERNO;
TRUNCATE TABLE ACESSO_FEDERACAO;
TRUNCATE TABLE ACOMPANHAMENTO;
TRUNCATE TABLE ANDAMENTO_INSTALACAO;
TRUNCATE TABLE ANDAMENTO_MARCADOR;
TRUNCATE TABLE ANDAMENTO_PLANO_TRABALHO;
TRUNCATE TABLE ANDAMENTO_SITUACAO;
TRUNCATE TABLE ANEXO;
TRUNCATE TABLE ANOTACAO;
TRUNCATE TABLE ARQUIVAMENTO;
TRUNCATE TABLE ASSINATURA;
TRUNCATE TABLE ATIVIDADE;
TRUNCATE TABLE ATRIBUTO_ANDAM_PLANO_TRAB;
TRUNCATE TABLE ATRIBUTO_ANDAMENTO;
TRUNCATE TABLE ATRIBUTO_INSTALACAO;
TRUNCATE TABLE AUDITORIA_PROTOCOLO;
TRUNCATE TABLE AVALIACAO_DOCUMENTAL;
TRUNCATE TABLE AVISO;
TRUNCATE TABLE BASE_CONHECIMENTO;
TRUNCATE TABLE BLOCO;
TRUNCATE TABLE CAMPO_PESQUISA;
TRUNCATE TABLE CATEGORIA;
TRUNCATE TABLE COMENTARIO;
TRUNCATE TABLE CONTROLE_PRAZO;
TRUNCATE TABLE CPAD;
TRUNCATE TABLE CPAD_AVALIACAO;
TRUNCATE TABLE CPAD_COMPOSICAO;
TRUNCATE TABLE CPAD_VERSAO;
TRUNCATE TABLE DOCUMENTO;
TRUNCATE TABLE DOCUMENTO_CONTEUDO;
TRUNCATE TABLE DOCUMENTO_GERACAO;
TRUNCATE TABLE EDITAL_ELIMINACAO;
TRUNCATE TABLE EDITAL_ELIMINACAO_CONTEUDO;
TRUNCATE TABLE EDITAL_ELIMINACAO_ERRO;
TRUNCATE TABLE EMAIL_GRUPO_EMAIL;
TRUNCATE TABLE ESTATISTICAS;
TRUNCATE TABLE ETAPA_TRABALHO;
TRUNCATE TABLE FEED;
TRUNCATE TABLE GRUPO_ACOMPANHAMENTO;
TRUNCATE TABLE GRUPO_BLOCO;
TRUNCATE TABLE GRUPO_EMAIL;
TRUNCATE TABLE GRUPO_FEDERACAO;
TRUNCATE TABLE GRUPO_PROTOCOLO_MODELO;
TRUNCATE TABLE INFRA_CAPTCHA;
TRUNCATE TABLE INFRA_CAPTCHA_TENTATIVA;
TRUNCATE TABLE INFRA_ERRO_PHP;
TRUNCATE TABLE INSTALACAO_FEDERACAO;
TRUNCATE TABLE ITEM_ETAPA;
TRUNCATE TABLE LEMBRETE;
TRUNCATE TABLE MAPEAMENTO_ASSUNTO;
TRUNCATE TABLE MARCADOR;
TRUNCATE TABLE MONITORAMENTO_SERVICO;
TRUNCATE TABLE NOTIFICACAO;
TRUNCATE TABLE NUMERACAO;
TRUNCATE TABLE OBSERVACAO;
TRUNCATE TABLE ORGAO_FEDERACAO;
TRUNCATE TABLE PARAMETRO_ACAO_FEDERACAO;
TRUNCATE TABLE PARTICIPANTE;
TRUNCATE TABLE PESQUISA;
TRUNCATE TABLE PLANO_TRABALHO;
TRUNCATE TABLE PROCEDIMENTO;
TRUNCATE TABLE PROTOCOLO;
TRUNCATE TABLE PROTOCOLO_FEDERACAO;
TRUNCATE TABLE PROTOCOLO_MODELO;
TRUNCATE TABLE PUBLICACAO;
TRUNCATE TABLE REABERTURA_PROGRAMADA;
TRUNCATE TABLE REL_ACESSO_EXT_PROTOCOLO;
TRUNCATE TABLE REL_ACESSO_EXT_SERIE;
TRUNCATE TABLE REL_AVISO_ORGAO;
TRUNCATE TABLE REL_BASE_CONHEC_TIPO_PROCED;
TRUNCATE TABLE REL_BLOCO_PROTOCOLO;
TRUNCATE TABLE REL_BLOCO_UNIDADE;
TRUNCATE TABLE REL_GRUPO_FED_ORGAO_FED;
TRUNCATE TABLE REL_ITEM_ETAPA_DOCUMENTO;
TRUNCATE TABLE REL_ITEM_ETAPA_SERIE;
TRUNCATE TABLE REL_ITEM_ETAPA_UNIDADE;
TRUNCATE TABLE REL_NOTIFICACAO_DOCUMENTO;
TRUNCATE TABLE REL_ORGAO_PESQUISA;
TRUNCATE TABLE REL_PROTOCOLO_ASSUNTO;
TRUNCATE TABLE REL_PROTOCOLO_ATRIBUTO;
TRUNCATE TABLE REL_PROTOCOLO_PROTOCOLO;
TRUNCATE TABLE REL_SERIE_PLANO_TRABALHO;
TRUNCATE TABLE REL_USUARIO_GRUPO_ACOMP;
TRUNCATE TABLE REL_USUARIO_GRUPO_BLOCO;
TRUNCATE TABLE REL_USUARIO_MARCADOR;
TRUNCATE TABLE REL_USUARIO_TIPO_PRIORIDADE;
TRUNCATE TABLE REL_USUARIO_TIPO_PROCED;
TRUNCATE TABLE REL_USUARIO_USUARIO_UNIDADE;
TRUNCATE TABLE REPLICACAO_FEDERACAO;
TRUNCATE TABLE RETORNO_PROGRAMADO;
TRUNCATE TABLE SECAO_DOCUMENTO;
TRUNCATE TABLE SERIE_ESCOLHA;
TRUNCATE TABLE SERIE_PUBLICACAO;
TRUNCATE TABLE SINALIZACAO_FEDERACAO;
TRUNCATE TABLE TEXTO_PADRAO_INTERNO;
TRUNCATE TABLE TIPO_PRIORIDADE;
TRUNCATE TABLE TIPO_PROCEDIMENTO_ESCOLHA;
TRUNCATE TABLE UNIDADE_FEDERACAO;
TRUNCATE TABLE UNIDADE_PUBLICACAO;
TRUNCATE TABLE USUARIO_FEDERACAO;
TRUNCATE TABLE VERSAO_SECAO_DOCUMENTO;

--Reset Sequências (versão Oracle > 11)

ALTER SEQUENCE SEQ_ACESSO RESTART START WITH 1;
ALTER SEQUENCE SEQ_ACESSO_EXTERNO RESTART START WITH 1;
ALTER SEQUENCE SEQ_ACOMPANHAMENTO RESTART START WITH 1;
ALTER SEQUENCE SEQ_ANDAMENTO_MARCADOR RESTART START WITH 1;
ALTER SEQUENCE SEQ_ANDAMENTO_PLANO_TRABALHO RESTART START WITH 1;
ALTER SEQUENCE SEQ_ANDAMENTO_SITUACAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_ANEXO RESTART START WITH 1;
ALTER SEQUENCE SEQ_ANOTACAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_ASSINATURA RESTART START WITH 1;
ALTER SEQUENCE SEQ_ATIVIDADE RESTART START WITH 1;
ALTER SEQUENCE SEQ_ATRIBUTO_ANDAM_PLANO_TRAB RESTART START WITH 1;
ALTER SEQUENCE SEQ_ATRIBUTO_ANDAMENTO RESTART START WITH 1;
ALTER SEQUENCE SEQ_AUDITORIA_PROTOCOLO RESTART START WITH 1;
ALTER SEQUENCE SEQ_AVALIACAO_DOCUMENTAL RESTART START WITH 1;
ALTER SEQUENCE SEQ_AVISO RESTART START WITH 1;
ALTER SEQUENCE SEQ_BASE_CONHECIMENTO RESTART START WITH 1;
ALTER SEQUENCE SEQ_BLOCO RESTART START WITH 1;
ALTER SEQUENCE SEQ_CONTROLE_INTERNO RESTART START WITH 1;
ALTER SEQUENCE SEQ_CPAD RESTART START WITH 1;
ALTER SEQUENCE SEQ_CPAD_AVALIACAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_CPAD_COMPOSICAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_CPAD_VERSAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_EDITAL_ELIMINACAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_EDITAL_ELIMINACAO_CONTEUDO RESTART START WITH 1;
ALTER SEQUENCE SEQ_EDITAL_ELIMINACAO_ERRO RESTART START WITH 1;
ALTER SEQUENCE SEQ_EMAIL_GRUPO_EMAIL RESTART START WITH 1;
ALTER SEQUENCE SEQ_ESTATISTICAS RESTART START WITH 1;
ALTER SEQUENCE SEQ_ETAPA_TRABALHO RESTART START WITH 1;
ALTER SEQUENCE SEQ_FEED RESTART START WITH 1;
ALTER SEQUENCE SEQ_GRUPO_ACOMPANHAMENTO RESTART START WITH 1;
ALTER SEQUENCE SEQ_GRUPO_EMAIL RESTART START WITH 1;
ALTER SEQUENCE SEQ_GRUPO_PROTOCOLO_MODELO RESTART START WITH 1;
ALTER SEQUENCE SEQ_ITEM_ETAPA RESTART START WITH 1;
ALTER SEQUENCE SEQ_MARCADOR RESTART START WITH 1;
ALTER SEQUENCE SEQ_MONITORAMENTO_SERVICO RESTART START WITH 1;
ALTER SEQUENCE SEQ_NOTIFICACAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_NUMERACAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_OBSERVACAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_PARTICIPANTE RESTART START WITH 1;
ALTER SEQUENCE SEQ_PLANO_TRABALHO RESTART START WITH 1;
ALTER SEQUENCE SEQ_PROTOCOLO RESTART START WITH 1;
ALTER SEQUENCE SEQ_PROTOCOLO_MODELO RESTART START WITH 1;
ALTER SEQUENCE SEQ_PUBLICACAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_REABERTURA_PROGRAMADA RESTART START WITH 1;
ALTER SEQUENCE SEQ_REL_PROTOCOLO_PROTOCOLO RESTART START WITH 1;
ALTER SEQUENCE SEQ_RETORNO_PROGRAMADO RESTART START WITH 1;
ALTER SEQUENCE SEQ_SECAO_DOCUMENTO RESTART START WITH 1;
ALTER SEQUENCE SEQ_SERIE_PUBLICACAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_SITUACAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_TEXTO_PADRAO_INTERNO RESTART START WITH 1;
ALTER SEQUENCE SEQ_TIPO_FORMULARIO RESTART START WITH 1;
ALTER SEQUENCE SEQ_TIPO_PRIORIDADE RESTART START WITH 1;
ALTER SEQUENCE SEQ_TIPO_PROCED_RESTRICAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_UNIDADE_PUBLICACAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_UPLOAD RESTART START WITH 1;
ALTER SEQUENCE SEQ_VERSAO_SECAO_DOCUMENTO RESTART START WITH 1;

/* As seguintes tabelas devem ser avaliadas para exclusão dos dados dos testes

TRUNCATE TABLE ATRIBUTO;
TRUNCATE TABLE CARGO_FUNCAO;
TRUNCATE TABLE CONTROLE_INTERNO;
TRUNCATE TABLE CONTROLE_UNIDADE;
TRUNCATE TABLE DOMINIO;
TRUNCATE TABLE EMAIL_UTILIZADO;
TRUNCATE TABLE GRUPO_CONTATO;
TRUNCATE TABLE GRUPO_UNIDADE;
TRUNCATE TABLE LOCALIZADOR;
TRUNCATE TABLE LUGAR_LOCALIZADOR;
TRUNCATE TABLE NOVIDADE;
TRUNCATE TABLE OPERACAO_SERVICO;
TRUNCATE TABLE ORDENADOR_DESPESA;
TRUNCATE TABLE PUBLICACAO_LEGADO;
TRUNCATE TABLE REL_CONTROLE_INTERNO_ORGAO;
TRUNCATE TABLE REL_CONTROLE_INTERNO_SERIE;
TRUNCATE TABLE REL_CONTROLE_INTERNO_TIPO_PROC;
TRUNCATE TABLE REL_CONTROLE_INTERNO_UNIDADE;
TRUNCATE TABLE REL_GRUPO_CONTATO;
TRUNCATE TABLE REL_GRUPO_UNIDADE_UNIDADE;
TRUNCATE TABLE REL_SERIE_ASSUNTO;
TRUNCATE TABLE REL_SITUACAO_UNIDADE;
TRUNCATE TABLE SERIE_RESTRICAO;
TRUNCATE TABLE SERVICO;
TRUNCATE TABLE SITUACAO;
TRUNCATE TABLE TIPO_FORMULARIO;
TRUNCATE TABLE TIPO_LOCALIZADOR;
TRUNCATE TABLE TIPO_PROCED_RESTRICAO;
TRUNCATE TABLE TITULO;

//Reset Sequências (versão Oracle > 11)


ALTER SEQUENCE SEQ_ATRIBUTO RESTART START WITH 1;
ALTER SEQUENCE SEQ_CONTROLE_UNIDADE RESTART START WITH 1;
ALTER SEQUENCE SEQ_DOMINIO RESTART START WITH 1;
ALTER SEQUENCE SEQ_EMAIL_UTILIZADO RESTART START WITH 1;
ALTER SEQUENCE SEQ_GRUPO_CONTATO RESTART START WITH 1;
ALTER SEQUENCE SEQ_GRUPO_UNIDADE RESTART START WITH 1;
ALTER SEQUENCE SEQ_LOCALIZADOR RESTART START WITH 1;
ALTER SEQUENCE SEQ_LUGAR_LOCALIZADOR RESTART START WITH 1;
ALTER SEQUENCE SEQ_NOVIDADE RESTART START WITH 1;
ALTER SEQUENCE SEQ_OPERACAO_SERVICO RESTART START WITH 1;
ALTER SEQUENCE SEQ_ORDENADOR_DESPESA RESTART START WITH 1;
ALTER SEQUENCE SEQ_SERIE_RESTRICAO RESTART START WITH 1;
ALTER SEQUENCE SEQ_SERVICO RESTART START WITH 1;
ALTER SEQUENCE SEQ_TIPO_LOCALIZADOR RESTART START WITH 1;

*/

/* Reconstrui as tabelas de log e auditoria e tabelas sequenciais correspondentes */
TRUNCATE TABLE INFRA_AUDITORIA;
TRUNCATE TABLE INFRA_LOG;
ALTER SEQUENCE SEQ_INFRA_AUDITORIA RESTART START WITH 1;
ALTER SEQUENCE SEQ_INFRA_LOG RESTART START WITH 1;

--Início - Habilitando as FKs

spool enable_fk.sql
select 'ALTER TABLE '||cons.table_name||' ENABLE CONSTRAINT '||constraint_name||';'
from   user_tables tabs
       INNER JOIN user_constraints cons on (cons.table_name = tabs.table_name)       
where cons.CONSTRAINT_TYPE = 'R';
spool off
@enable_fk.sql;
/
--Fim - Habilitando as FKs

/*
Sobre a última linha abaixo, a tabela de sequência anual de protocolo de processos pode ser qualquer um dos formatos abaixo (de acordo com a configuração da numeração de protocolo):
seq_[ano]_org_sip_[id sip]
seq_[ano]_org_sei_[cod sei]
seq_[ano]_uni_sip_[id sip]
seq_[ano]_uni_sei_[cod sei]
*/

delete from infra_sequencia where nome_tabela like 'seq_%_uni_sei_%';
delete from infra_sequencia where nome_tabela like 'seq_%_uni_sip_%';
delete from infra_sequencia where nome_tabela like 'seq_%_org_sei_%';
delete from infra_sequencia where nome_tabela like 'seq_%_org_sip_%';

update infra_sequencia set num_atual=0 where nome_tabela='infra_log';
update infra_sequencia set num_atual=0 where nome_tabela='infra_navegador';

/********************************************************************************************************************************************************/



